name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub         
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Deploy Docker containers on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          run: |
          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST bash << EOF
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            sudo docker pull $DOCKERHUB_USERNAME/basic3tier-api:latest
            sudo docker pull $DOCKERHUB_USERNAME/basic3tier-ui:latest

            sudo docker network create my3tier || true

            # Run Postgres
            sudo docker rm -f my3tier-db || true
            sudo docker run -d --network my3tier --name my3tier-db \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_PASSWORD=admin123 \
              -e POSTGRES_DB=basic3tier \
              -p 5432:5432 \
              postgres

            # Espera o Postgres estar pronto
            echo "Waiting for Postgres..."
            sleep 10

            # Run the API
            sudo docker rm -f my3tier-api || true
            sudo docker run -d --network my3tier --name my3tier-api \
              -p 5000:80 \
              -e ConnectionStrings__Basic3Tier="Host=my3tier-db;Port=5432;Database=basic3tier;Username=postgres;Password=admin123" \
              $DOCKERHUB_USERNAME/basic3tier-api:latest

            sudo docker rm -f my3tier-ui || true
            sudo docker run -d --network my3tier --name my3tier-ui \
              -p 80:80 \
              -e API_URL="http://$EC2_HOST:5000/" \
              $DOCKERHUB_USERNAME/basic3tier-ui:latest
          EOF
